### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by kaos-addict** [KaOS-Community-Packages/gitkraken#1]
Here is what I get when launching via terminal:
`$ gitkraken 
(electron) ipc module is deprecated. Use require("electron").ipcMain instead.
state:  update-not-available
(electron) loadUrl is deprecated. Use loadURL instead.
App load time: 409ms
state:  checking-for-update
state:  update-not-available`
Then nothing happen and I ctrl-c to cancel

**Comment by forostm** [comment]
Please try now, I add "libgnome-keyring" to depends.

**Comment by kaos-addict** [comment]
Works now, thanks!

**Comment by zaakiy** [comment]
Trying to launch in KDE Neon gives me the following (tried both the DEB installer and the tar gz with same result)
```
# ./gitkraken
libgnome-keyring.so.0: cannot open shared object file: No such file or directory
Error: libgnome-keyring.so.0: cannot open shared object file: No such file or directory
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/GitKraken/resources/app.asar/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/opt/GitKraken/resources/app.asar/node_modules/keytar/lib/keytar.js:58:4)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/GitKraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/v1_5_0.js:11:14)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at /opt/GitKraken/resources/app.asar/src/js/utils/FolderLoader.js:16:27
    at Array.forEach (native)
    at FolderLoader (/opt/GitKraken/resources/app.asar/src/js/utils/FolderLoader.js:11:34)
    at Object.<anonymous> (/opt/GitKraken/resources/app.asar/src/appBootstrap/upgradeScripts/versionScripts/index.js:5:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/GitKraken/resources/app.asar/src/appBootstrap/upgradeScripts/index.js:7:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at EventEmitter.<anonymous> (/opt/GitKraken/resources/app.asar/src/appBootstrap/main.js:117:5)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)

```
